name: CI

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  tests:
    name: Lint & Deploy
    runs-on: ubuntu-latest
    container: node:14-alpine
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint

  docker-build:
    needs: tests
    name: Build Docker Container
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: get tag
        run: echo "GIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          registry: ${{ secrets.AWS_ECR_REGISTRY }}
      - name: Build and push landing Docker image
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            ${{ secrets.AWS_ECR_REGISTRY }}/landing/landing:${{ env.GIT_TAG }}

  deploy:
    needs: docker-build
    name: Deploy to AWS EKS
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Checkout helm charts
        uses: actions/checkout@v3
        with:
          repository: Rabbit-mx/helm-charts
          token: ${{ secrets.GH_PAT }}
          path: helm
      - name: get tag
        run: echo "GIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Connect to EKS Cluster
        run: aws eks --region ${{ secrets.AWS_DEFAULT_REGION }} update-kubeconfig --name ${{ secrets.AWS_EKS_CLUSTER }}
      - uses: azure/setup-kubectl@v1
        with:
          version: 'v1.23.3'
      - uses: azure/setup-helm@v1
        with:
          version: 'v3.8.0'
      - name: deploy to cluster
        run: helm upgrade --install --namespace=default -f ./infra/helm/default-values.yaml --set image.tag=${{ env.GIT_TAG }} landing ./helm/landing

